#pragma once

#include "CoreMinimal.h"

KELLERKIND_API DECLARE_LOG_CATEGORY_EXTERN(LogKellerkind, Log, All);
KELLERKIND_API DECLARE_LOG_CATEGORY_EXTERN(LogKKGen, Log, All);
KELLERKIND_API DECLARE_LOG_CATEGORY_EXTERN(LogKKHorror, Log, All);
