[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Kellerkind/Maps/L_MainMenu.L_MainMenu
EditorStartupMap=/Game/Kellerkind/Maps/L_Prolog_Haus.L_Prolog_Haus
GlobalDefaultGameMode=/Script/Kellerkind.KKGameMode

[/Script/Engine.RendererSettings]
; --- KELLERKIND Renderpfad: Cinematic Realistic Horror ---
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.MotionBlur=True
r.DefaultFeature.AntiAliasing=2
r.AntiAliasingMethod=4
r.Lumen.HardwareRayTracing=True
r.Lumen.TranslucencyReflections.FrontLayer.Enable=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.Nanite=1
r.Nanite.ProjectEnabled=True
r.SkinCache.CompileShaders=True
r.RayTracing=True
r.RayTracing.Shadows=True
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=8
r.VolumetricCloud=0
r.SSGI.Enable=0
r.Substrate=1
r.HairStrands.Enable=1
r.SubsurfaceScattering=1
r.SeparateTranslucency=True
r.GBufferFormat=3
r.PostProcessing.PropagateAlpha=False
r.Streaming.PoolSize=3000
r.MipMapLODBias=0
bEnableVirtualTextures=True
r.VirtualTextures=1
r.VT.EnableAutoImport=True

[/Script/Engine.PhysicsSettings]
DefaultGravityZ=-980.000000
PhysicsPrediction=(bEnablePhysicsPrediction=False)
bSubstepping=True
MaxSubstepDeltaTime=0.008333
MaxSubsteps=6

[/Script/Engine.AudioSettings]
DefaultSoundClassName=/Game/Kellerkind/Audio/SC_Master.SC_Master
DefaultSubmixName=/Game/Kellerkind/Audio/SM_Master.SM_Master
bAllowVirtualizedSounds=True

[/Script/AIModule.AISystem]
bEnableDebuggerPlugin=True

[/Script/Engine.CollisionProfile]
+Profiles=(Name="KKCreature",CollisionEnabled=QueryAndPhysics,ObjectTypeName="Pawn",CustomResponses=((Channel="Camera",Response=ECR_Ignore)),HelpMessage="Kellerkind-Kreaturen")
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel1,DefaultResponse=ECR_Block,bTraceType=True,bStaticObject=False,Name="Interaction")
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel2,DefaultResponse=ECR_Block,bTraceType=True,bStaticObject=False,Name="Weapon")
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel3,DefaultResponse=ECR_Overlap,bTraceType=True,bStaticObject=False,Name="Vision")
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel4,DefaultResponse=ECR_Overlap,bTraceType=True,bStaticObject=False,Name="LightProbe")
