; KELLERKIND Grafik-Presets: 0=Low 1=Medium 2=High 3=Ultra 4=Cinematic

[ShadowQuality@0]
r.Shadow.Virtual.Enable=0
r.ShadowQuality=2
r.Shadow.MaxResolution=1024
[ShadowQuality@1]
r.Shadow.Virtual.Enable=1
r.Shadow.Virtual.ResolutionLodBiasLocal=2.0
[ShadowQuality@2]
r.Shadow.Virtual.Enable=1
r.Shadow.Virtual.ResolutionLodBiasLocal=1.0
[ShadowQuality@3]
r.Shadow.Virtual.Enable=1
r.Shadow.Virtual.ResolutionLodBiasLocal=0.0
[ShadowQuality@4]
r.Shadow.Virtual.Enable=1
r.Shadow.Virtual.ResolutionLodBiasLocal=-0.5

[GlobalIlluminationQuality@0]
r.DynamicGlobalIlluminationMethod=0
[GlobalIlluminationQuality@1]
r.DynamicGlobalIlluminationMethod=1
r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution=8
r.Lumen.HardwareRayTracing=0
[GlobalIlluminationQuality@2]
r.DynamicGlobalIlluminationMethod=1
r.Lumen.HardwareRayTracing=0
[GlobalIlluminationQuality@3]
r.DynamicGlobalIlluminationMethod=1
r.Lumen.HardwareRayTracing=1
[GlobalIlluminationQuality@4]
r.DynamicGlobalIlluminationMethod=1
r.Lumen.HardwareRayTracing=1
r.Lumen.ScreenProbeGather.DownsampleFactor=8

[ReflectionQuality@0]
r.ReflectionMethod=2
[ReflectionQuality@4]
r.ReflectionMethod=1
r.Lumen.Reflections.HardwareRayTracing=1

[FoliageQuality@0]
foliage.DensityScale=0.4
[FoliageQuality@4]
foliage.DensityScale=1.0

[ViewDistanceQuality@0]
r.ViewDistanceScale=0.5
[ViewDistanceQuality@4]
r.ViewDistanceScale=1.4

[EffectsQuality@0]
r.VolumetricFog=0
r.Niagara.QualityLevel=0
[EffectsQuality@4]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=4
r.Niagara.QualityLevel=4
